# Generated by Django 3.1 on 2020-08-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200810_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='keyword',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='keyword',
            new_name='keywords',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
